### ISSUE TITLE
Unable to generate Vermittulungs code.

### ISSUE THREAD

**Issue by victorvg17** [iamnotturner/vaccipy#450] opened 2021-06-12 09:32 UTC
Hi,
Thanks for the wonderful tool. 
I have tried running the cli tool version in both mac and Linux environment for more than 2 hrs.
The following message keeps repeating on the terminal:
`
2021-06-12 11:22:06.633   impfterminservice   [inf] [   ]   Browser-Cookie generiert: *MjDw==
2021-06-12 11:22:06.835   impfterminservice   [err] [   ]   Anfrage wurde von der Botprotection geblockt
2021-06-12 11:22:06.836   impfterminservice   [err] [   ]   Die Cookies müssen manuell im Browser generiert werden
2021-06-12 11:22:06.836   impfterminservice   [inf] [   ]   Browser-Cookies generieren
2021-06-12 11:22:08.276   impfterminservice   [inf] [   ]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-12 11:23:16.007   impfterminservice   [war] [   ]   Du hast jetzt 30 Sekunden Zeit möglichst viele Elemente im Chrome Fenster anzuklicken. Das Fenster schließt sich automatisch.
`
Could you please confirm whether this is expected and waiting time of more than a couple of hours is normal?
Thanks,
Victor

**Comment by iamnotturner** [comment] 2021-06-12 09:37
hey victor, yes there are problems right now with the cookie generation.
Do you speak German? Since this is a duplicate of #449 I'd close this one and keep the other one updated

**Closed by iamnotturner** 2021-06-12 09:37 UTC

**Comment by victorvg17** [comment] 2021-06-12 09:46
Thanks for linking the issue. I understand a bit German. I will follow the linked thread.
